### ISSUE TITLE
(conda-env-initialize-interactive-shells) messes up 'M-x shell' on my Windows box

### ISSUE THREAD

**Issue by JoshOBrien** [necaris/conda.el#10]
Hello,

I've just recently discovered conda, and have gotten it mostly set up and working. I really appreciate the package, but no matter what I do, including `(conda-env-initialize-interactive-shells)` in my init file seems to kill my ability to launch a shell by doing `M-x shell`. (Commenting it out fixes the problem.)

I am running Vincent Goulet's [distribution](https://vigou3.github.io/emacs-modified-windows/) of the following version of Emacs: `GNU Emacs 25.2.1 (x86_64-w64-mingw32) of 2017-04-24` on a Windows 7 laptop. I experience the problem when I launch emacs by doing `emacs -q --load /path/to/my-init.el` where `my-init.el` is a pared down init file containing just the following:

```
;; "my-init.el"
(package-initialize)
(elpy-enable)

;; Temp fix for problem whose fuller solution is referenced here:
;; https://github.com/jorgenschaefer/elpy/issues/887
(setq python-shell-completion-native-enable nil)

(custom-set-variables
  '(conda-anaconda-home "C:/Users/Josh/Anaconda3"))
(require 'conda)
;; Unfortunately, this kills my ability to launch
;; into a shell with `M-x shell`. In buffer, I get:
;; "Symbol’s value as variable is void: buffer"
(conda-env-initialize-interactive-shells)
```

**Comment by respatialized** [comment]
I've also experienced this issue on Ubuntu 17.04.

**Comment by monomon** [comment]
Did some searching and this is the breaking commit https://github.com/necaris/conda.el/commit/c61b35e8a2e7e3ead06ab9feb6760cee12abd6d8

Perhaps instead of `buffer` the author meant to use `args`. Or alternatively we could add an optional argument `buffer`. But I could be missing something in the implementiation.

Either way, it's a bug.

**Comment by monomon** [comment]
I created a [pull request](https://github.com/necaris/conda.el/pull/11) for this issue. The change also addresses a couple other bugs that were breaking the shell in windows.

If anyone wants to review the change it would be great. elisp newbie here.

**Comment by necaris** [comment]
As #11 is confirmed to fix this I'm closing this. Please do reopen if something's still broken.
