### ISSUE TITLE
Support for mamba

### ISSUE THREAD

**Issue by PhilippeNoel1** [necaris/conda.el#105]
As mamba is now a recommended replacement for conda, it could be nice to support it

source: https://mamba.readthedocs.io/en/latest/user_guide/mamba.html

**Comment by PhilippeNoel1** [comment]
I tested for mamba and it works. In fact mamba is just like conda, so I just edit as the following:
```elisp
(use-package conda
  :custom
  (conda-anaconda-home "~/mambaforge")
  (conda-env-home-directory "~/mambaforge"))
```

I tested with micromamba and it does not work at the same way. There is no `conda-meta` does not exist, ... 
So if you want to work with conda.el, use conda or mamba but not micromamba

**Comment by necaris** [comment]
Could you please open a PR adding the default directories to the search path?

—
Rami Chowdhury
“A mind all logic is like a knife all blade - it makes the hand bleed that uses it.” - Rabindranath Tagore

**Comment by PhilippeNoel1** [comment]
I can but actually there is only `~/anaconda3` as candidate for conda-env-home. Should I add the `~/mamba` and maybe `~/miniconda` as candidates and iterate through them to search the conda path ?

**Comment by necaris** [comment]
Philippe ***@***.***> writes:

> I can but actually there is only ~/anaconda3 as candidate for conda-env-home. Should I add the ~/mamba and maybe ~/miniconda as candidates and iterate
> through them to search the conda path ?

That would be a great improvement, please do!

--
Rami Chowdhury
A mind all logic is like a knife all blade - it makes the hand bleed that uses it.
  -- Rabindranath Tagore

**Comment by PhilippeNoel1** [comment]
Ok no problem ! I will work on it after my vacation :)

**Comment by PhilippeNoel1** [comment]
Merged with https://github.com/necaris/conda.el/pull/106
Can close this issue
