### ISSUE TITLE
Cannot deactivate conda environment

### ISSUE THREAD

**Issue by cemeroncel** [necaris/conda.el#118]
Hello,

I am running Emacs 28.1 with native compilation and Conda 4.13. I have two `conda` environments. The command `conda-env-list` correctly shows them, and I can also activate them with `conda-env-activate`. However, when I try to deactivate them using `conda-env-deactivate` I get the following error:

`conda--call-json-subcommand: could not parse JSON stream: "invalid token near 'ArgumentError'", "<string>", 2, 13, 14`

I have `miniconda` instead of `anaconda` if it is related.

**Comment by ScottH** [comment]
I'm seeing the same issue on emacs 28.1, miniconda, and I'm on OSX

**Comment by necaris** [comment]
Could you post the output of the command `conda shell.posix+json deactivate $ENVIRONMENT` (where `$ENVIRONMENT` is one of your available environments)?

**Comment by ScottH** [comment]
OK. Here you go. Thanks!
-Scott

(base) ***@***.*** ~ % *conda activate stats*
(stats) ***@***.*** ~ % *conda shell.posix+json deactivate
stats*

ArgumentError: deactivate does not accept arguments
remainder_args: ['stats']


But I can do this:

(stats) ***@***.*** ~ % *conda shell.posix+json deactivate*
{
  "path": {
    "PATH": [
      "/Users/scott/miniconda3/bin",
      "/Users/scott/miniconda3/condabin",
      "/usr/local/bin",
      "/usr/bin",
      "/bin",
      "/usr/sbin",
      "/sbin",
      "/Library/TeX/texbin",
      "/opt/X11/bin",
      "/Library/Apple/usr/bin"
    ]
  },
  "vars": {
    "export": {
      "CONDA_PREFIX": "/Users/scott/miniconda3",
      "CONDA_SHLVL": 1,
      "CONDA_DEFAULT_ENV": "base",
      "CONDA_PROMPT_MODIFIER": "(base) ",
      "CONDA_EXE": "/Users/scott/miniconda3/bin/conda",
      "_CE_M": "",
      "_CE_CONDA": "",
      "CONDA_PYTHON_EXE": "/Users/scott/miniconda3/bin/python"
    },
    "unset": [
      "CONDA_PREFIX_1"
    ],
    "set": {
      "PS1": "(base) "
    }
  },
  "scripts": {
    "activate": [],
    "deactivate": []
  }
}%

**Comment by ScottH** [comment]
I've tried the fix where you removed the argument to the deactivate command, but now I get this when I try to deactivate an env.

conda--get-deactivation-parameters: Wrong number of arguments: #[(subcommand env-dir) "<C6> ^X
<C7>=<83>^M^@Ȃ^N^@<C9>^Z<CA><CB>^H
^K^L%^]<CC>^M!^^^U<CD>^N^V<CE>\"<83>+^@<CF>^N^U!<82>3^@<D0>^N^U<D1><D2><D3><D4>%,<87>" [conda system-type sh subcommand env-dir cmd conda--get-executable-path windows-nt "cmd.exe" "posix" ...] 6 ("/Users/scott/.emacs.d/elpa/conda-20220710.1740/conda.elc" . 16112)], 1

**Comment by ScottH** [comment]
conda-call-json-subcommand is expecting that all commands come with env-dir. 
Maybe make the env-dir an optional argument so the function can handle the deactivate command? 


(defun conda--call-json-subcommand (subcommand env-dir) ....

**Comment by ScottH** [comment]
I tried this and it seems to work:

(defun conda--call-json-subcommand (subcommand &optional env-dir)
  "Call Conda SUBCOMMAND on ENV-DIR returning JSON."
  (unless env-dir (setq env-dir ""))
....

**Comment by ScottH** [comment]
I’ll try to dig in and check this tonight once the baby is asleep. Thanks!
Scott
