### ISSUE TITLE
conda-env-name-to-dir errors

### ISSUE THREAD

**Issue by gmoutso** [necaris/conda.el#129]
https://github.com/necaris/conda.el/blob/a65ed0084876366fd1b238bb2b8b36ee75ac98d8/conda.el#L349
Should the quote above be removed. Otherwise I get
Wrong type argument: consp, "/home/me/.virtualenvs/"
Regards!

**Comment by necaris** [comment]
When do you get that error? When running `conda-env-activate`?

**Comment by gmoutso** [comment]
Yes, after I load the library virtualenvwrapper required by traad.

**Comment by gmoutso** [comment]
If I replace the line with `(if (stringp venv-location)` it works
