### ISSUE TITLE
Question about Auto Activation

### ISSUE THREAD

**Issue by vikigenius** [necaris/conda.el#13]
I have a query regarding the auto activation using dir-locals or environment.yml file
Why is auto activation activating the virtual environment every time i switch buffers?
Isn't it enough to activate only once when the buffer is created initially with the file name?

**Comment by necaris** [comment]
@vikigenius sorry for the delayed reply. Please note that the `conda` environment state is buffer-local, so if you switch away from an activated buffer that state is no longer active, and must be restored when you switch back.

**Comment by vikigenius** [comment]
@necaris Thanks for the reply.  I am new to emacs and lisp though, but i thought buffer local variables need to be set only once for the first time when the file is opened and then they retain their state even with switching?

**Comment by necaris** [comment]
@vikigenius Yes, that's correct -- they retain their state _in that buffer_, but any global state (for example, the active Python script path for any Python integrations you may have) does need to be reset.
