### ISSUE TITLE
Add conda-config (similar to elpy-config) command to re-evaluate cached values

### ISSUE THREAD

**Issue by epruesse** [necaris/conda.el#134]
`conda--config` caches the parsed output of `conda config --show --json`. If that's wrong the first time round, there are constant weird error messages.

In my case, I was getting `Wrong type argument: arrayp, nil` on all `conda-*` functions called. Turns out `conda--config` contained `(json-parse-error "invalid token near 'sh'" "<string>" 1 2 2)`. It took forever to realize was actually the cached value, not a current error...

Perhaps having `conda-config` similar to `elpy-config` to re-load and show the (cached) configuration would be a not-too-complex fix to this and similar issues?

**Comment by necaris** [comment]
That's definitely an interesting thought!

Elmar Pruesse ***@***.***> writes:

> conda--config caches the parsed output of conda config --show --json. If that's wrong the first time round, there are
> constant weird error messages.
>
> In my case, I was getting Wrong type argument: arrayp, nil on all conda-* functions called. Turns out conda--config
> contained (json-parse-error "invalid token near 'sh'" "<string>" 1 2 2). It took forever to realize was actually the
> cached value, not a current error...
>
> Perhaps having conda-config similar to elpy-config to re-load and show the (cached) configuration would be a not-too-complex
> fix to this and similar issues?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.


--
Rami Chowdhury
A mind all logic is like a knife all blade - it makes the hand bleed that uses it.
  -- Rabindranath Tagore

**Comment by necaris** [comment]
Does #136 look like it'll do the trick?
