### ISSUE TITLE
elpy-use-ipython: elpy-use-ipython is deprecated

### ISSUE THREAD

**Issue by notuntoward** [necaris/conda.el#14]
When I run `conda-env-activate`, and select an environment, I get the following warning:

`elpy-use-ipython: elpy-use-ipython is deprecated; see https://elpy.readthedocs.io/en/latest/ide.html#interpreter-setup`

If, instead, I have `(conda-env-autoactivate-mode t)` in my .emacs, then I get an error when I start emacs:

`Error (use-package): elpy/:init: elpy-use-ipython is deprecated; see https://elpy.readthedocs.io/en/latest/ide.html#interpreter-setup`

This is on emacs 25.3.1 and elpy 1.18.0

**Comment by necaris** [comment]
@notuntoward I'm sorry for the delayed response -- for some reason I haven't been seeing notifications from this repo. I hope you've been able to solve your issue in the meantime.

I double-checked and `conda.el` isn't depending on (or calling any functionality from) `elpy` so I'm not sure how to reproduce or resolve this. On the assumption that this is more to do with your `elpy` configuration, I'm going to close it, but please do reopen if you have more details!
