### ISSUE TITLE
conda info command in eshell doesn't reflect active env

### ISSUE THREAD

**Issue by dangirsh** [necaris/conda.el#15]
Reproduce by running `conda info` in a vanilla eshell configuration (Emacs 25) and see it report "active environment : None".

It's no big deal, but might be worth fixing / documenting to avoid confusing people.

**Comment by necaris** [comment]
@dangirsh sorry for the delayed response, and thanks for noticing! I've opened #31 to fix this -- if there's a chance you could have a look, that would be appreciated, and I'll probably merge it in the next few days.
