### ISSUE TITLE
conda--get-name-from-env-yml fails on environment names that include hyphens

### ISSUE THREAD

**Issue by dangirsh** [necaris/conda.el#16]
Currently, the environment file is searched with the following regexp:

```
"name:[ ]*\\(\\w+\\)[ ]*$"
```

For whatever syntax class that's active in this part of the code, "w+" seems to exclude hyphens. The result is that environments with hyphens fail to be automatically detected via `environment.yml`.

**Comment by necaris** [comment]
This should be fixed by @danking's patch: https://github.com/necaris/conda.el/pull/18
