### ISSUE TITLE
Using conda-environments with org-babel

### ISSUE THREAD

**Issue by Aquan1412** [necaris/conda.el#21]
Is it possible to set org-babel to use the conda environment settings? When I start a standard python session in emacs, it works flawlessly and uses the conda environment. However, when I'm using org-babel it always falls back to using the system version of python (and ipython).

**Comment by necaris** [comment]
@Aquan1412 I'm sorry for the delay in looking into this; which version of Emacs and `conda.el` have you been using? Provided I activate my conda environment _before_ I run any commands, I'm able to see it working:
```
#+BEGIN_SRC python :session :exports both :results raw drawer 
  import sys
  (sys.version_info, sys.prefix)
#+END_SRC

#+RESULTS:
:RESULTS:
(sys.version_info(major=3, minor=5, micro=6, releaselevel='final', serial=0), '/home/necaris/.anaconda3/envs/py35')
:END:
```
However, if I don't activate my environment till after I've run a command or two, it seems Emacs starts the session with my system Python and reuses it; short of killing the active Python session, I don't know if there's a way to get Emacs to pick up the changed settings.

**Comment by necaris** [comment]
@Aquan1412 I'm going to go ahead and close this, since I haven't been able to reproduce it; if you are able to provide more details on the issue please do reopen it!
