### ISSUE TITLE
Activate environments residing in custom paths

### ISSUE THREAD

**Issue by johannes-mueller** [necaris/conda.el#26]
Usually I have my conda envs either in the project root directory in `_venv` or (sometimes) in some arbitrary directory. So not a named environment from `conda create -n <name>` but a prefixed from `conda create -p <path>`. Is there a chance to load those kind prefixed (not named) environments, too?

**Comment by necaris** [comment]
@johannes-mueller sorry for the delay, for some reason I haven't been getting notifications for new issues. That's definitely on my roadmap, thanks for asking!

**Comment by johannes-mueller** [comment]
Implemented in #41.
