### ISSUE TITLE
conda-env-autoactivate-mode only takes effect on second visit to buffer

### ISSUE THREAD

**Issue by adbull** [necaris/conda.el#29]
`conda-env-autoactivate-mode` doesn't take effect until you open a buffer, switch away, and then switch back. The implementation adds advice to `switch-to-buffer`, which is not called the first time a buffer is loaded.

**Comment by necaris** [comment]
Thank you @adbull that's a good catch! Let me look into how to fix it!

**Comment by tim-hilt** [comment]
Don't want to bump or anything, but are there any news?

Thanks for making the package! It's been working great!

**Comment by arthurcgusmao** [comment]
Hi, perhaps using `set-buffer` instead of `switch-to-buffer` can be a fix, since the former is used by many other functions in `window.el`.

**Comment by necaris** [comment]
I haven't had any issues with this functionality since this was opened, so I'm closing as inactive; please reopen if necessary!
