### ISSUE TITLE
"s-join: Wrong type argument: sequencep, 47" followed by "s-join: Wrong type argument: listp, ..."

### ISSUE THREAD

**Issue by sampotter** [necaris/conda.el#38]
This may be related to a few other recent issues (#32, #36, #15, #19), but I wasn't sure.

When I run `conda-env-activate`, I first get the following error:

`s-join: Wrong type argument: sequencep, 47`

If I run it again, I get:

`s-join: Wrong type argument: listp, "/Users/sfp/miniconda3/bin/:/Users/sfp/miniconda3/condabin/:/usr/local/bin/:/usr/bin/:/bin/:/usr/sbin/:/sbin/:/Library/TeX/texbin/:/opt/X11/bin/:/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10/:/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10/:/Applications/Emacs.app/Contents/MacOS/libexec/"`

Output of `M-x version`:

`GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-30`

Using version 20190531.1807 installed from melpa.

Please let me know if there's anything I can do to help out with debugging this.

**Comment by necaris** [comment]
@sampotter thank you for reporting this! I'm hoping these will be fixed by #34, which should be built and on melpa in the next few hours -- I'll close it for now, optimistically, but please reopen if you update and are still seeing the issue.

**Comment by sampotter** [comment]
This worked for me. Thank you!
