### ISSUE TITLE
conda-env-deactivate doesn't restore PATH

### ISSUE THREAD

**Issue by notmgsk** [necaris/conda.el#42]
In an eshell buffer:
1. `(conda-env-initialize-eshell)`
2. `echo $PATH`
3. `$ activate env-name`
4. `echo $PATH`
5. `$ deactivate`
6. `echo $PATH`

I would assume that 6. and 2. would produce the same result (as is the case when running the above in e.g. `bash`). However, `PATH` is unchaged by 5. meaning that the env `env-name` is still activate at 6.

**Comment by necaris** [comment]
Sorry for the delayed response -- thanks for finding this!

**Comment by necaris** [comment]
Hopefully closed by #23
