### ISSUE TITLE
Help with custom conda directory

### ISSUE THREAD

**Issue by anihm136** [necaris/conda.el#45]
I'm having some trouble setting the conda home directory. I have it installed at `/home/user/miniconda3`. I have set the `conda-anaconda-home` variable to the above directory, but it does not detect the environments I have created.

Also, when I manually set the environment using `M-x conda-env-activate-path`, it does not seem to make any difference to Flycheck (import of packages installed only in the conda environment show up as errors).

How do I set it up correctly? Any help is appreciated.

**Comment by necaris** [comment]
@anihm136 does this seem related to #36 by any chance?

**Comment by anihm136** [comment]
@necaris I don't think so. I don't have any clashing names for one, and even setting the path specifically doesnt seem to be making a difference. How can I check if an env is activated after running the command?

**Comment by anihm136** [comment]
Update: I've still not been able to get this to work. I've tried setting the home directory to my installation (`/home/user/miniconda3`) as well as the envs folder inside it. Even `conda-env-activate-path` does not work with the absolute path to the env directory

**Comment by anihm136** [comment]
Yes, that helped! I'm able to activate conda envs now. Thanks!
