### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by dan-passaro** [necaris/conda.el#5]
On Windows, the \<env\>\Scripts\ directory doesn't contain `python.exe` so even after activating the env with conda.el, `M-x run-python`, eshell etc. still use the system Python.

The env-specific `python.exe` is in the parent directory, i.e. the root \<env\> directory.

Can try pushing a PR to fix sometime next week.

**Comment by JoshOBrien** [comment]
Looking forward to seeing how you fix this. I've been trying and failing to get [pyvenv](https://github.com/jorgenschaefer/pyvenv) to work on my Windows 7 box, and this appears to be the issue there as well. (I say that mostly because copying `python.exe` and (in my application) `python35.dll` from the root `<env>` directory into `<env>/Scripts` seems to get everything working like I'd hope.)

**Comment by fkgruber** [comment]
This issue still seems to be happening in the latest version
I had to create a symbolic link of the python.exe inside the Script directory of the enviroment variable

The problem is the function:
```
(defvar conda-env-executables-dir  ;; copied from virtualenv.el
  (if (eq system-type 'windows-nt) "Scripts" "bin")
  "Name of the directory containing executables.  It is system dependent.")
```
The executable is in the root of the enviroment.

In my environment, for example, i have:

> 04/20/2018  11:37 AM            19,208 api-ms-win-crt-utility-l1-1-0.dll
> 11/19/2018  01:57 PM           332,336 concrt140.dll
> 01/29/2020  08:40 PM    <DIR>          conda-meta
> 01/29/2020  07:55 PM    <DIR>          DLLs
> 10/12/2019  08:23 PM    <DIR>          include
> 10/12/2019  08:23 PM    <DIR>          Lib
> 01/29/2020  08:40 PM    <DIR>          Library
> 10/12/2019  08:23 PM    <DIR>          libs
> 07/08/2019  02:03 PM            12,769 LICENSE_PYTHON.txt
> 11/19/2018  01:57 PM           627,440 msvcp140.dll
> 09/03/2019  01:29 PM           627,992 msvcp140.dll.c~.conda_trash
> 11/19/2018  01:57 PM            30,960 msvcp140_1.dll
> 09/03/2019  01:29 PM            31,512 msvcp140_1.dll.c~.conda_trash
> 11/19/2018  01:57 PM           205,552 msvcp140_2.dll
> 08/09/2019  07:35 PM            95,232 python.exe
> 08/09/2019  07:35 PM           438,272 python.pdb
> 08/09/2019  07:34 PM            51,712 python3.dll
> 08/09/2019  07:34 PM         3,748,864 python37.dll
> 08/09/2019  07:34 PM         9,539,584 python37.pdb
> 08/09/2019  07:35 PM            93,696 pythonw.exe
> 08/09/2019  07:35 PM           438,272 pythonw.pdb
> 03/14/2020  02:17 PM    <DIR>          Scripts
> 10/12/2019  08:23 PM    <DIR>          tcl
> 10/12/2019  08:23 PM    <DIR>          Tools
> 04/20/2018  11:37 AM         1,016,584 ucrtbase.dll
> 11/19/2018  01:57 PM           366,320 vccorlib140.dll
> 11/19/2018  01:57 PM           153,840 vcomp140.dll
> 11/19/2018  01:57 PM            85,232 vcruntime140.dll
> 09/03/2019  01:29 PM            85,784 vcruntime140.dll.c~.conda_trash
> 08/09/2019  07:34 PM           515,584 venvlauncher.exe
> 08/09/2019  07:34 PM           515,072 venvwlauncher.exe
>               62 File(s)     19,877,185 bytes
>               11 Dir(s)  77,436,432,384 bytes free
> 
> (tf2) s:\anaconda64\envs\tf2>pwd
>

**Comment by necaris** [comment]
I don't have a Windows license handy so I'm not able to test this easily, but I might have time to create a VM and try it this weekend. @fkgruber can you list what executables are in your `scripts` directory?

**Comment by fkgruber** [comment]
Hi
Note that I created the symbolic link to python.exe. It was not there.
I have:
(tf2) s:\anaconda64\envs\tf2\Scripts>ls -l
ls -l
total 2820
-rw-rw-r--    2 fred     fred            74 Aug 09  2019 2to3-script.py
-rwxrwxr-x    2 fred     fred         40960 Jul 23  2019 2to3.exe
-rwxrwxr-x    1 fred     fred        106331 Mar 14 15:00 autopep8.exe
-rwxrwxr-x    1 fred     fred        106343 Mar 07 16:49 black.exe
-rwxrwxr-x    1 fred     fred        106344 Mar 07 16:49 blackd.exe
-rwxrwxr-x    1 fred     fred        103275 Jan 28 23:03 chardetect.exe
-rwxrwxr-x    2 fred     fred        103330 Dec 12 15:32 convert-caffe2-to-onnx.exe
-rwxrwxr-x    2 fred     fred        103330 Dec 12 15:32 convert-onnx-to-caffe2.exe
-rw-rw-r--    3 fred     fred           225 Jan 27 12:51 easy_install-script.py
-rwxrwxr-x    3 fred     fred         40960 Jan 26  2019 easy_install.exe
-rwxrwxr-x    1 fred     fred        103317 Jan 28 23:09 estimator_ckpt_converter.exe
-rwxrwxr-x    1 fred     fred           402 Jan 29 19:08 f2py-script.py
-rwxrwxr-x    3 fred     fred           156 Jan 15 15:59 f2py.bat
-rwxrwxr-x    3 fred     fred         74752 Jan 22 12:04 f2py.exe
-rw-rw-r--    2 fred     fred           238 Oct 14 16:55 freeze_graph-script.py
-rwxrwxr-x    2 fred     fred         40960 Jul 23  2019 freeze_graph.exe
-rwxrwxr-x    1 fred     fred        103287 Jan 28 23:03 google-oauthlib-tool.exe
-rw-rw-r--    2 fred     fred            72 Aug 09  2019 idle-script.py
-rwxrwxr-x    2 fred     fred         40960 Jul 23  2019 idle.exe
-rw-rw-r--    2 fred     fred           209 Jun 07  2019 markdown_py-script.py
-rwxrwxr-x    2 fred     fred         40960 Jan 26  2019 markdown_py.exe
-rw-rw-r--    3 fred     fred           212 Jan 27 12:51 pip-script.py
-rwxrwxr-x    3 fred     fred         40960 Jan 26  2019 pip.exe
-rwxrwxr-x    1 fred     fred        106343 Jan 29 19:27 pt2to3.exe
-rwxrwxr-x    1 fred     fred        106343 Jan 29 19:27 ptdump.exe
-rwxrwxr-x    1 fred     fred        106345 Jan 29 19:27 ptrepack.exe
-rwxrwxr-x    1 fred     fred        106343 Jan 29 19:27 pttree.exe
-rwxrwxr-x    1 fred     fred        106336 Mar 14 15:00 pycodestyle.exe
-rw-rw-r--    2 fred     fred            57 Aug 09  2019 pydoc-script.py
-rwxrwxr-x    2 fred     fred         40960 Jul 23  2019 pydoc.exe
-rwxrwxr-x    1 fred     fred        103266 Jan 28 23:03 pyrsa-decrypt.exe
-rwxrwxr-x    1 fred     fred        103266 Jan 28 23:03 pyrsa-encrypt.exe
-rwxrwxr-x    1 fred     fred        103264 Jan 28 23:03 pyrsa-keygen.exe
-rwxrwxr-x    1 fred     fred        103287 Jan 28 23:03 pyrsa-priv2pub.exe
-rwxrwxr-x    1 fred     fred        103260 Jan 28 23:03 pyrsa-sign.exe
-rwxrwxr-x    1 fred     fred        103264 Jan 28 23:03 pyrsa-verify.exe
lrwxrwxrwx    1 root     root            33 Mar 14 14:17 python.exe -> ../python.exe
-rw-rw-r--    2 fred     fred           233 Oct 14 16:55 saved_model_cli-script.py
-rwxrwxr-x    2 fred     fred         40960 Jul 23  2019 saved_model_cli.exe
-rw-rw-r--    1 fred     fred           207 Jan 29 19:09 tensorboard-script.py
-rwxrwxr-x   21 fred     fred         74752 Dec 19 18:31 tensorboard.exe
-rw-rw-r--    2 fred     fred           243 Oct 14 16:55 tf_upgrade_v2-script.py
-rwxrwxr-x    2 fred     fred         40960 Jul 23  2019 tf_upgrade_v2.exe
-rw-rw-r--    2 fred     fred           231 Oct 14 16:55 tflite_convert-script.py
-rwxrwxr-x    2 fred     fred         40960 Jul 23  2019 tflite_convert.exe
-rw-rw-r--    2 fred     fred           231 Oct 14 16:55 toco-script.py
-rwxrwxr-x    2 fred     fred         40960 Jul 23  2019 toco.exe
-rw-rw-r--    2 fred     fred           238 Oct 14 16:55 toco_from_protos-script.py
-rwxrwxr-x    2 fred     fred         40960 Jul 23  2019 toco_from_protos.exe
-rw-rw-r--    1 fred     fred           203 Sep 23 14:21 wheel-script.py
-rwxrwxr-x    1 fred     fred         40960 Jul 23  2019 wheel.exe
-rwxrwxr-x    1 fred     fred        106335 Mar 14 15:01 yapf.exe

**Comment by necaris** [comment]
Thank you! I'm afraid I'm not likely to get to this very soon (nor do I 
have a Windows machine to test on) but I'll try to look at this this 
weekend.
