### ISSUE TITLE
conda-env-current-name not defined: How to set global-mode-string?

### ISSUE THREAD

**Issue by johanwiden** [necaris/conda.el#69]
conda-env-current-name appears to be no longer defined, but the README still says that it is to be used for
updating global-mode-string.
How are we now supposed to put the current environment name in the mode string?

**Comment by arthurcgusmao** [comment]
@johanwiden Sorry for the mistake and thank you for opening this issue. Please see the commit message of the abovementioned fix; now this problem should be fixed (the variable has been restored, and is being set appropriately). I will open a merge request.

**Comment by necaris** [comment]
@johanwiden thank you for the bug report! I'm hopeful we've fixed this with @arthurcgusmao's PR #70 but please let us know if that's not the case!
