### ISSUE TITLE
Unable to activate base environment

### ISSUE THREAD

**Issue by Invarianz** [necaris/conda.el#74]
By following the guides on the landing page I'm unable to get the base environment to work.
I guess this comes from the fact that the base environment is not listed in `anaconda3/envs`.
Doing a clone of the base environment into a second environment with a different name works.
Currently I'm only setting
```
(use-package conda
  :ensure t
  :custom
  (conda-anaconda-home "/opt/anaconda3/")
  :config
  (conda-env-initialize-eshell))
```

Another workaround is to create a softlink called `base` in `anaconda3/envs` that points back to `anaconda3/`.

**Comment by necaris** [comment]
@Invarianz Can you not do `(conda-env-activate "base")`?

**Comment by Invarianz** [comment]
Exactly, without my extra symlink it does not work. As I said, I think this is related to the fact that `base` is not listed in `anaconda3/envs`.

**Comment by necaris** [comment]
@Invarianz can you confirm if this is still true with the latest from Melpa? This functionality should be present from https://github.com/necaris/conda.el/pull/67 so I'm surprised it doesn't work for you.

**Comment by necaris** [comment]
Closing as no comments since #67, please reopen if necessary!
