### ISSUE TITLE
void-variable prev-env in conda-with-env

### ISSUE THREAD

**Issue by jonmoore** [necaris/conda.el#76]
Calling functions using `conda-with-env` currently results in a `void-variable` error against `prev-env`.

To fix this, the name `prev-env` at https://github.com/necaris/conda.el/blob/9f7eea16e9ad3eb34fe3d1cbd9d6162b8046c2f8/conda.el#L373 should be renamed to `prev-env-path`, in line with the similar renamings in https://github.com/necaris/conda.el/commit/5dc78b55682e924c40501bfc00cc40f86e6661f7

**Comment by necaris** [comment]
@jonmoore thank you for the catch & the debugging! Looks like a really simple fix -- any interest in submitting a PR?
