### ISSUE TITLE
buffer local variable `conda-anaconda-home' not working

### ISSUE THREAD

**Issue by AirManH** [necaris/conda.el#77]
If I set `conda-anaconda-home` as a _buffer local variable_, `conda-env-activate` can not activate the correct conda env.

### Configuration

1. In `init file`:
    
    ``` emacs lisp
    (use-package conda)
    ```
2. My python project is organized as:

   ``` example
   .
   ├── .dir-locals.el
   └── src
       └── main.py
   ```
3. In `.dir-locals.el`:

   ``` emacs lisp
   ((python-mode . ((conda-anaconda-home . "/home/user/programs/miniconda3/"))))
   ```

### Operations

1. open `main.py`
2. `M-x conda-env-activate`, choose environment `base`, `enter`
3. `*Message*` buffer shows:
   ```
   if: Error: executing command ""/home/user/.anaconda3/bin/conda" ..activate "bash" "/home/user/programs/miniconda3/"" produced error code 127
   ```

## Specifications

- conda-20200818.1614
- emacs 27.1
- conda 4.9.2
- Arch Linux
- x86_64 Linux 5.9.14-arch1-1

**Comment by AirManH** [comment]
I did some debugging and found out what caused this error.

As the code shown below, in the line 190, the statement `(with-current-buffer standard-output` in function `conda--get-path-prefix` will override the buffer local variable `conda-anaconda-home`.

https://github.com/necaris/conda.el/blob/9f7eea16e9ad3eb34fe3d1cbd9d6162b8046c2f8/conda.el#L185-L197

If you change the code into this:

``` emacs lisp
 (defun conda--get-path-prefix (env-dir) 
   "Get a platform-specific path string to utilize the conda env in ENV-DIR. 
 It's platform specific in that it uses the platform's native path separator." 
   (message "%s" conda-anaconda-home)  ;;; <========= /home/user/programs/miniconda3/
   (s-trim 
    (with-output-to-string 
      (with-current-buffer standard-output 
        (let* ((conda-executable-path 
                (concat (file-name-as-directory conda-anaconda-home) 
                        (file-name-as-directory conda-env-executables-dir) 
                        "conda"))
               (tmp (message "%s" conda-anaconda-home))  ;;; <========= /home/user/.anaconda3/
```

The first `message` prints: `/home/user/programs/miniconda3/`, and the second prints: `/home/user/.anaconda3/`

**Comment by necaris** [comment]
@AirManH thanks for the report and the debugging! It looks like capturing the current value of `conda-anaconda-home` outside the `with-current-buffer` block will fix this -- any interest in submitting a PR?
