### ISSUE TITLE
End of file during parsing

### ISSUE THREAD

**Issue by notuntoward** [necaris/conda.el#84]
The latest version of conda.el coming from elpa won't compile.  Here's the error message I get when I try:

```
Compiling file c:/Users/scott/.emacs.d/elpa/conda-20210407.1802/conda.el at Thu Apr  8 09:13:21 2021
conda.el:401:1:Error: End of file during parsing
```

**Comment by necaris** [comment]
I'm so sorry -- that's my mistake, got overexcited making an update. Fix on the way.

**Comment by notuntoward** [comment]
Thanks!

**Comment by necaris** [comment]
@notuntoward should be fixed now, apologies for delay!
