### ISSUE TITLE
Interactive-Shell Issue: <env_name>: command not found

### ISSUE THREAD

**Issue by hnisonoff** [necaris/conda.el#87]
I am having trouble getting conda.el to work well with my interactive shell (M-x shell).
When I run `M-x conda-env-activate <env_name>`  and then run `M-x shell` I get:
`<env_name>: command not found`

Presumably conda.el is missing the `conda activate` part when initializing the shell, but I'm not sure why?

Here is my setup, which is slightly non-standard because my conda home director is in `/anaconda3/` instead of `~anaconda3/`. 

```
(use-package conda
  :ensure t
  :init
  (progn
    (require 'conda)
    (custom-set-variables
     '(conda-anaconda-home "/anaconda3/"))
    (setq conda-env-home-directory (expand-file-name "/anaconda3/"))
    (conda-env-initialize-interactive-shells)
    (conda-env-initialize-eshell)
    (conda-env-autoactivate-mode t)
))
```
Thanks!

**Comment by louisdecharson** [comment]
Having the same here ! Any news @hnisonoff  ?

**Comment by louisdecharson** [comment]
I've tried to debug it and for some reason `activate-command` is not set after 
```elisp
(activate-command (if (eq system-type 'windows-nt
                                   '("activate")
                                   '("conda" "activate"))))
```
e.g.:
```elisp
(message "activate command: %s" activate-command)
```
yields:  `activate-command: nil`

I've ended up modifying the function `conda-env-shell-init` in `conda.el` as:

```elisp
;;;###autoload
(defun conda-env-shell-init (process)
  "Activate the current env in a newly opened shell PROCESS."
  ;; TODO: maintain compatibility with an older Conda version. Do we
  ;; check the Conda version and cache it?
  ;; TODO: make sure the shell has been set up for `conda activate`!
  ;; Do we need to `eval' the conda activation script every time?
  (let* ((activate-command (if (eq system-type 'windows-nt
                                   '("activate")
                                   '("conda" "activate"))))
         (activate-command (if (not activate-command) '("conda" "activate") activate-command))
         (full-command (append activate-command `(,conda-env-current-name "\n")))
         (command-string (combine-and-quote-strings full-command)))
    (comint-send-string process command-string)
    ))
```

**Comment by louisdecharson** [comment]
Hi @necaris,
To me your code should work just fine, ie:
```elisp
((activate-command (if (eq system-type 'windows-nt
                                   '("activate")
                                   '("conda" "activate"))))
```
I don't understand why it does not.
So I am happy to submit a PR but I feel my solution is more a plaster than anything else and a more appealing solution would fix the `let activate-command` part.

**Comment by louisdecharson** [comment]
Ok got the issue, it's was a simple parenthesis problem, I've submitted a PR to fix it:
https://github.com/necaris/conda.el/pull/95
