### ISSUE TITLE
How to actually run python in emacs once you've run conda-activate-env?

### ISSUE THREAD

**Issue by patfla** [necaris/conda.el#92]
I have conda installed and correctly configured so that it seems that I can successfully target one of my conda environments.  From the *Messages* buffer:

> Mark set [2 times]
> Switched to conda environment: d:/pat/miniconda3/envs/cubeenv/
> Quit [2 times]

That's correct - however, when I run-python and then try to import a module that's in that environment it fails in confusing ways, and in particular it tells me that the python I'm running is the default python installed outside conda which is found under c:\users\patf\appdata\local\programs\python.

**Comment by necaris** [comment]
@patfla did you have any luck with this? I'm seeing the correct Python run with `run-python` -- absent any more details I'll close this as inactive, but if you're still seeing the error we can try to diagnose further.
