### ISSUE TITLE
conda-env-activate can't find miniconda on Windows

### ISSUE THREAD

**Issue by notuntoward** [necaris/conda.el#99]
If I run:

` (conda-env-activate "base")`

I get the error: "No such conda environment: base"

But I do have a base environment:
```
(base) C:\Users\scott>conda env list
# conda environments:
#
                         C:\JupyterLab\resources\jlab_server
base                  *  C:\Users\scott\miniconda3
```
This used to work when I was using the full anaconda3 distribution, but on this machine, I'm using miniconda, which has a different path.  Maybe that's the problem.

**Comment by necaris** [comment]
@notuntoward have you set the path to your conda installation
appropriately? Look at `conda-anaconda-home` in the docs.

notuntoward ***@***.***> writes:

> If I run:
>
> (conda-env-activate "base")
>
> I get the error: "No such conda environment: base"
>
> But I do have a base environment:
>
> (base) C:\Users\scott>conda env list
> # conda environments:
> #
>                          C:\JupyterLab\resources\jlab_server
> base                  *  C:\Users\scott\miniconda3
>
> This used to work when I was using the full anaconda3 distribution, but on this machine, I'm using miniconda, which has a different path. Maybe that's
> the problem.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.


--
Rami Chowdhury
Come scale computation with me at Coiled!

**Comment by notuntoward** [comment]
Oh, right.  That's it.  With a modified path, the conda package works as before.
